### ISSUE TITLE
메타몽 구현

### ISSUE THREAD

**Issue by 1daero** [1daero/branch-practice#1]
## 설명

포켓몬스터 캐릭터 중 메타몽을 구현하고자 합니다.

## Tasks

- [x] 메타몽 컨셉 작성
- [x] 메타몽 외관 디자인
- [x] 메타몽 특성 구현
- [ ] 메타몽 스킬 구현

## References

https://www.google.com
